[build]
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  BUNDLE_VERSION = "2.2.0"
  RUBY_VERSION = "2.7.2"
  NODE_VERSION = "14"

[[plugins]]
  package = "@netlify/plugin-skip-node-install"
